### ISSUE TITLE
Crate Issue for Itertools 0.4.11 for Rust 1.0 & 1.1

### ISSUE THREAD

**Issue by jramapuram** [bluss/rust-itertools#106]
Running travis builds [here](https://travis-ci.org/jramapuram/hal/builds/115508664) and seem to see an issue for itertools. Is there some breaking change that prevents 1.0 & 1.1 from working with the new version? It seems to work fine for rustc > 1.1

```rust
 Downloading itertools v0.4.11
Unable to get packages from source
Caused by:
  failed to parse manifest at `/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.4.11/Cargo.toml`
Caused by:
  expected a value of type `string` for the key `lib.name`
```

**Comment by bluss** [comment]
itertools has required Rust 1.1 since version 0.4.2, and Rust 1.2 since 0.4.11. The bump is not in the changelog, but the README was updated to say requires Rust 1.2+. See this commit https://github.com/bluss/rust-itertools/commit/7541e7c1f13d302a1d07a2b654fef78fcc65146f

**Comment by bluss** [comment]
The error you are citing was probably caused by https://github.com/bluss/rust-itertools/commit/89a2d3146a3513ab8a70012be574abd408cb6b49

**Comment by jramapuram** [comment]
Fair enough. I will update my project requirements.
