### ISSUE TITLE
prepend/append convenience methods

### ISSUE THREAD

**Issue by Kha** [bluss/rust-itertools#107]
I have quite some instances of combining `iter::once` and `Iterator::chain` in my code, do you think it would make sense to add two convenience methods for this? Looking at `Vec`, `push` may be a better name for `append`, but I'm not sure what to call `prepend` then. The argument order of `prepend` may be confusing, either way.

**Comment by bluss** [comment]
I'm so so thrilled, mainly because when repeated it results in a very layered and inefficient iterator.

Evolution has taken us to a point where [PutBack](https://bluss.github.io/rust-itertools/doc/itertools/struct.PutBack.html) basically provides the prepend version though.

**Comment by Kha** [comment]
I see, that is a fair concern. I think I'll stick with `once+chain` then, it's still more readable than `PutBack::with_value`.
