### ISSUE TITLE
bound function not correct

### ISSUE THREAD

**Issue by kindlychung** [bluss/rust-itertools#118]
See here: https://github.com/bluss/rust-itertools/blob/master/src/adaptors.rs#L142

Isn't it missing the case `self.phase && a < b`?

**Comment by kindlychung** [comment]
`!self.phase && a > b || (self.phase && a < b)` seems correct to me.

**Comment by bluss** [comment]
It has a quickcheck test here https://github.com/bluss/rust-itertools/blob/master/tests/quick.rs#L306

Can you form a testcase that fails?

**Comment by kindlychung** [comment]
I don't know quickcheck well enough at the moment, but check this out: 


```
extern crate itertools;

use itertools::InterleaveShortest;

fn main() {
	let a = vec![1u32, 2u32, 3u32]; 
	let b = vec![1u32, 2u32, 3u32, 4u32, 5u32, 6u32]; 
	let mut i = InterleaveShortest::new(a.into_iter(), b.into_iter());
	let x = i.next(); 
	println!("{:?}", i.size_hint());
}
```

This prints `(4, Some(5))`, which in my opinion is not really accurate, I would expect `(5, Some(5))`.

**Comment by kindlychung** [comment]
This produces `(5, Some(5))`: 


```rust
        let bound = |a: usize, b: usize| -> Option<usize> {
            use std::cmp::min;
            2usize.checked_mul(min(a, b))
//                .and_then(|lhs| lhs.checked_add(if !self.phase && a > b { 1 } else { 0 }))
                .and_then(|lhs| lhs.checked_add(if  !self.phase && a > b || (self.phase && a < b)  { 1 } else { 0 }))
        };
```

**Comment by bluss** [comment]
nice, thanks a lot!
