### ISSUE TITLE
Wouldn't it be more flexible to use `F: FnMut(&Option<I::Item>, &Option<I::Item>) -> bool` instead?

### ISSUE THREAD

**Issue by kindlychung** [bluss/rust-itertools#128]
https://github.com/bluss/rust-itertools/blob/master/src/adaptors.rs#L556

Wouldn't it be more flexible to use `F: FnMut(&Option<I::Item>, &Option<I::Item>) -> bool` instead?

**Comment by bluss** [comment]
It's an internal API so.. being more flexible matters if we want to implement something new with it?
