### ISSUE TITLE
Kmerge fails

### ISSUE THREAD

**Issue by tailhook** [bluss/rust-itertools#134]
This simple test crashes itertools:
```
#[test]
fn kmerge_reverse() {
    let its = vec![3, 2, 1, 0].into_iter().map(|s| (s..10).step(4));
    it::assert_equal(its.kmerge(), (0..10));
}
```
The error is:
```
        thread 'kmerge_reverse' panicked at 'Failed assertion Some(1) == Some(0) for iteration 0', src/lib.rs:1585
```
If I print the sequences I'm getting the following:
```
---- kmerge_reverse stdout ----
        [[3, 7], [2, 6], [1, 5, 9], [0, 4, 8]]
```
So nothing wrong with the sequences.

I also have an issue with getting the wrong (unsorted) data. But I have not found a simple example to reproduce.

**Comment by tailhook** [comment]
Ah, okay, it's not a crash it actually is wrong result :)

**Comment by tailhook** [comment]
Here is a test with more clear output:
```
#[test]
fn kmerge_reverse() {
    let its = vec![3, 2, 1, 0].into_iter().map(|s| (s..10).step(4));
    assert_eq!(
        its.kmerge().collect::<Vec<_>>(),
        (0..10).collect::<Vec<_>>());
}
```
Output:
```
        thread 'kmerge_reverse' panicked at 'assertion failed: `(left == right)` (left: `[1, 0, 2, 3, 4, 5, 6, 7, 8, 9]`, right: `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`)', tests/tests.rs:416
```

**Comment by bluss** [comment]
Thanks for the bug report!

**Comment by tailhook** [comment]
This produces a bug in my application. So if you're not looking at it, can you give me some pointers where the error might be?

**Comment by bluss** [comment]
src/kmerge.rs has the heap logic. Prime suspicion would be that the bespoke heap logic is to blame. I'm a bit curious why the quickcheck doesn't catch it though. Probably because it's always testing exactly three input iterators.

**Comment by tailhook** [comment]
Looks good. Thanks!

**Comment by bluss** [comment]
0.4.17 released with the fix. In hindsight, it's obvious that the existing quickcheck for kmerge didn't exercise it fully (always used a heap of size 3 or smaller).
