### ISSUE TITLE
Add Windows-like Iterator that returns static-sized tuple elements instead of slices.

### ISSUE THREAD

**Issue by Robbepop** [bluss/rust-itertools#141]
The [Windows](https://doc.rust-lang.org/std/slice/struct.Windows.html) iterator in the std lib returns its values as slices of elements.
This makes it unpleasant to work with since pattern matching and borrowing of slices is more restricted than (for example) for tuples.

Besides that a tuple-based Windows iterator should not involve runtime overhead and should make it possible to make compile time assumptions about the correctness of the implementation. For example, it can be checked at compiletime if accesses to iterator elements are "out-of-bounds".

E.g.:

```rust
    let primes = &[2, 3, 5, 7, 11, 13, 17, ...];
    for (fst, snd) in primes.iter().windows(2) {
        println!("({}, {})", fst, snd);
    }
```

**Comment by bluss** [comment]
Needs to take into account that integer parameters like `2` are runtime information and tuple arity is type-level compile time information. Would work fine with a type-level kind of parameterization, either `.windows2()` or `.windows::<Pair>()` and so on.

**Comment by Robbepop** [comment]
Ah dang. You are right, I haven't thought about that. Maybe with the [typenum](http://paholg.com/typenum/typenum/index.html) crate one could work around this until associated constants land in Rust, if ever?

**Comment by bluss** [comment]
I don't think typenum supports tuples, or is the solution we want? We can do something simpler with traits. Should look at other cases like .combinations() as well as windows.

**Comment by Robbepop** [comment]
I do not know exactly how he did it, but in [Crate: Generic Array](http://fizyk20.github.io/generic-array/generic_array/) the owner uses [typenum::uint](http://fizyk20.github.io/generic-array/typenum/uint/index.html) in order to create a generic statically sized array. This could be used in a similar way to create an easy-to-use windows(N) iterator that can have tuples (compile-time-constant size types) as iterator elements. =)
[ArrayLength](http://fizyk20.github.io/generic-array/generic_array/trait.ArrayLength.html) is where the magic happens according to the owner of the generic-array crate.

**Comment by bluss** [comment]
They use an interesting trick where they just make a struct of the correct size. Instead of [T; 4] they have `struct { struct { T, T }, struct { T, T } }`.

**Comment by mmun** [comment]
I was looking for this today and sort of hoped that it would be
```rust
let primes = &[2, 3, 5, 7, 11, 13, 17, ...];
for (fst, snd) in iwindow!(primes.iter(), 2) {
    println!("({}, {})", fst, snd);
}
```

**Comment by bluss** [comment]
Like in #151, I think ` for (fst, snd) in primes.tuple_windows()` can become a reality soon.
