### ISSUE TITLE
Add a generic Chain iterator

### ISSUE THREAD

**Issue by Robbepop** [bluss/rust-itertools#142]
It would be nice to have a ```Chain``` iterator in this library that could chain several iterators together instead of just too as it is supported in the std lib at the moment.
This should behave similar to the currently implemented ```Zip::new((..))```.

__Simple-silly example code:__

```rust
let v = vec![4,5,6];
let words: Vec<String> = vec!["Hello", "World", "!"];
for x in Chain::new((&[1,2,3], v.iter(), words.iter().map(|word| word.len()))) {
    println!("{}", x);
}
```

Important would be a possibility to also create a way to chain a bunch of iterators over **mutable** elements to obtain yet another iterator over mutable data.

__A (possibly buggy) example code:__

```rust
let (ax, bx, cx) = (&[1,2,3], &[4,5,6], &[7,8,9]);
for mut x in Chain::new((ax.iter_mut(), bx.iter_mut(), cx.iter_mut())) {
    x = x*x + x;
}
```

**Comment by bluss** [comment]
If it works for general iterators, it will work for the mutable-reference carrying ones as well.

**Comment by bluss** [comment]
I'm unsure if this is needed. It's not such a big thing as .zip(), since chain doesn't need to flatten anything. Chaining .chain() calls should work fine.

**Comment by Robbepop** [comment]
To me it would be a superior syntax in cases where I need to chain more than two iterators together. But you are right that a Chain iterator isn't as needed as a Zip iterator was.

**Comment by bluss** [comment]
I will decline this up front for now. Thanks anyway.

Supporting "n-ary" constructions in Rust just requires hacks, traits over several tuple types and so on. In this case it is not worth it (does not buy us enough), and the regular chaining style is truly n-ary for any *n*, not just a finite trait implementation list.
