### ISSUE TITLE
Add reductions()

### ISSUE THREAD

**Issue by nikic** [bluss/rust-itertools#147]
Unless I missed it, there doesn't seem to currently exist a function to get an iterator of the intermediate values of a reduction function. Here is an example of how this can be used to easily create a cumulative sum iterator:

```rust
#[test]
fn test_cumsum() {
    let expected = vec![1, 3, 6, 10, 15];
    let result: Vec<_> = (1..6).reductions(|a,b| a+b).collect();
    assert_eq!(expected, result);
}
```

For me this use-case up when I needed a cumulative sum over an addition operator without inverse, to optimize sums of certain structure.

Does this seem like something that could be part of this library? (The name "reductions" is not great, as rust uses "fold" instead of "reduce", there's probably some other term for this.)

---

I came up with the following implementation for my own use, though me being new to Rust it likely does everything wrong:

```rust
pub struct Reductions<I, R> where I : Iterator {
    iter: I,
    reductor: R,
    prev: Option<I::Item>
}

impl<I, R> Iterator for Reductions<I, R>
        where I: Iterator, I::Item: Clone,
              R: FnMut(I::Item, I::Item) -> I::Item {
    type Item = I::Item;

    fn next(&mut self) -> Option<Self::Item> {
        self.iter.next().map(|item| {
            let value = match self.prev.take() {
                Some(prev) => (self.reductor)(prev, item),
                None => item
            };
            self.prev = Some(value.clone());
            value
        })
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        self.iter.size_hint()
    }
}

impl<I, R> ExactSizeIterator for Reductions<I, R>
    where I: Iterator, I::Item: Clone,
          R: FnMut(I::Item, I::Item) -> I::Item {}

pub trait IteratorExt : Iterator {
    fn reductions<R>(self, reductor: R) -> Reductions<Self, R>
            where R: FnMut(Self::Item, Self::Item) -> Self::Item,
                  Self: Sized {
        Reductions {
            iter: self,
            reductor: reductor,
            prev: None
        }
    }
}

impl<T> IteratorExt for T where T: Iterator { }
```

**Comment by nikic** [comment]
Note that as suggested above I'm using a variant where the first element of the reductions() iterator will match the first element of the original iterator. [Closure](https://clojuredocs.org/clojure.core/reductions) has another variant which allows you to specify an initial element, so that it will be the first element of the returned iterator instead.

**Comment by bluss** [comment]
It's similar to [scan](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.scan)

**Comment by nikic** [comment]
@bluss You're right, I have missed that function. This does seem to be easy to implement on top of scan().

Sorry for the noise!
