### ISSUE TITLE
.fold_while is using a `self` receiver

### ISSUE THREAD

**Issue by bluss** [bluss/rust-itertools#168]
This is a bit weird, since fold_while allows stopping the fold early.

**Comment by bluss** [comment]
@regexident  Collective oversight?

See also this reasoning for more context: (from #167)

> I don't think it's the best that Iterator::fold uses a self receiver (reason: it's less general, and a &mut I where I: Iterator then cannot use the I type’s specific fold implementation).

**Comment by bluss** [comment]
FYI I'm considering writing an RFC for adding fold_while to rust's libcore. The reason is that it is a generalization of all *internal iteration* features in the iterator trait (methods `max, fold, find, position` and more).

To realize the generalization, the method `Iterator::fold_while` needs to return the `FoldWhile` control enum itself (think about how  you would implement `.fold_while()` for `Chain` and you'll see why — it's composable only that way).

**Comment by regexident** [comment]
> FYI I'm considering writing an RFC for adding fold_while to rust's libcore. The reason is that it is a generalization of all internal iteration features in the iterator trait (methods all, any, max, fold, find, position and more).

That's great!

> To realize the generalization, the method Iterator::fold_while needs to return the FoldWhile control enum itself (think about how you would implement .fold_while() for Chain and you'll see why — it's composable only that way).

Could you elaborate briefly on why this is the case? With a minimal code sample maybe, if it helps?

**Comment by bluss** [comment]
Code example in https://github.com/rust-lang/rust/compare/master...bluss:fold-while-2?expand=1#diff-d93bf2799d551e25b17e877b23a37db3R574

The highlighted line is .fold_while() for chain.

I think it's needed when you call .fold_while() on multiple component iterators -- you need to know if that component was exhausted (FoldWhile::Continue) or the user wants to break (FoldWhile::Done).

The way composability fell out this way, it feels rustic and like the right choice. Having to add a macro to abstract the control flow is well.. is that Rustic in itself?

**Comment by regexident** [comment]
> I think it's needed when you call .fold_while() on multiple component iterators -- you need to know if that component was exhausted (FoldWhile::Continue) or the user wants to break (FoldWhile::Done).

Ah, now I see. Makes sense now, albeit being slightly unergonomic for the simpler cases.

> The way composability fell out this way, it feels rustic and like the right choice. Having to add a macro to abstract the control flow is well.. is that Rustic in itself?

I'm all for composability. Making `FoldWhile<T>` implement `Into<T>` should eliminate most ergonomic deficits of returning `FoldWhile<T>` from `fn fold_while(…)`, I think:

```rust
let foo: bool = (0..10).fold_while(|acc, item| { … }).into();
```

**Comment by bluss** [comment]
- Draft rfc for fold while as regeneralization of internal iteration in Iterator https://github.com/bluss/rfcs/blob/composable-internal-iteration/text/0000-composable-internal-iteration.md
- discussion along the same kind of ideas https://medium.com/@veedrac/rust-is-slow-and-i-am-the-cure-32facc0fdcb#.3cq1mirru

**Comment by bluss** [comment]
The Pre-RFC is kind of abandoned, because it doesn't work smoothly with `?` https://internals.rust-lang.org/t/pre-rfc-fold-ok-is-composable-internal-iteration/4434

Fold while will return `FoldWhile<T>` in the next version of itertools, so that it has the composable formulation.

**Comment by bluss** [comment]
The whole fold_ok ordeal feels like a side track. Wouldn't fold_while in itertools 0.6's shape be better for libcore?

**Comment by regexident** [comment]
Sounds good to me. But then again you're clearly the expert on this one. 😅

**Comment by bluss** [comment]
oh no help I don't want to be the expert :sweat_smile:

**Comment by regexident** [comment]
> oh no help I don't want to be the expert 😅

Well, I'd love to see `fold_while` in libcore! But I don't feel by any means familiar enough with the type shenanigans around `?`/Carrier/etc and the wider scope of libcore/stdlib to make an informed statement on the feasibility of adding it to libcore. 😐
