### ISSUE TITLE
Add `partition_by_index`?

### ISSUE THREAD

**Issue by birkenfeld** [bluss/rust-itertools#173]
Would work like `.enumerate().partition()`, except that the two partition collections get only the original items, not the `(index, item)` tuple.

Use case: Put elements of an iterator (which may have even or odd # of elements) into two alternating Vecs.

If you think this is a good addition, I'll make a PR.

**Comment by bluss** [comment]
I think using itertools' `.enumerate().partition_map()` covers this. It should be simple to make with that version of partition.

**Comment by birkenfeld** [comment]
It is kind of clunky though:
```.enumerate().partition_map(|(i, v)| if condition { Either::Left(v) } else { Either::Right(v) })```
But I know you can't put every two-line function into itertools :)

Another version that might be interesting though:
```distribute() -> B where B: Distribute<Self::Item>```
and impls for `Distribute` for tuples of `(FromIterator, ...)`?

Or maybe `distribute(x)` where `x` is a tuple of `&mut FromIterator`...

**Comment by bluss** [comment]
I don't quite manage to fill in the blanks there. We use `Extend` to be able to build a collection piece by piece, but how does distribute work?

**Comment by birkenfeld** [comment]
Sorry. Just like `Extend`, but distributing the items round-robin over several collections. In effect building 2 ... n at the same time.

**Comment by bluss** [comment]
I see, a general round robin distributer sounds more fun than partition_by_index.

I'm not sure what our editorial standards should be in itertools, we're getting more serious and less experimental by now, I'm not so fond of anything that requires helper traits right now. tuples/tuple_windows got a pass just because they were that awesome..

**Comment by birkenfeld** [comment]
That's true, `tuples` and friends are great...

I think I'll make a pass at implementation anyway, even if in the end it's just for fun :)

**Comment by bluss** [comment]
Hey, this is not bad. Maybe a trait to handle the "add" part (and maybe it can do it by ref instead of passing collections by value.

[playground](http://play.integer32.com/?gist=234c48d97ded1943b6a3da26caf82fe5&version=stable)

```rust
fn add<T, U, A, B>((mut t, mut u): (T, U), elt: (A, B)) -> (T, U)
    where T: Extend<A>, U: Extend<B>,
{
    t.extend(Some(elt.0));
    u.extend(Some(elt.1));
    (t, u)
}
    
fn main() {
    println!("{:?}", (0..12).tuples().fold((Vec::new(), Vec::new()), add));
    // ([0, 2, 4, 6, 8, 10], [1, 3, 5, 7, 9, 11])
}
```

**Comment by bluss** [comment]
I don't know, is this a better way to express it?

```rust
extern crate itertools;

use itertools::Itertools;

#[derive(Debug)]
pub struct ExtendTuple<T>(T);

impl<'a, A, B, T, U> Extend<(A, B)> for ExtendTuple<&'a mut (T, U)>
    where T: Extend<A>, U: Extend<B>,
{
    fn extend<I: IntoIterator<Item=(A, B)>>(&mut self, iter: I) {
        for (x, y) in iter {
            (self.0).0.extend(Some(x));
            (self.0).1.extend(Some(y));
        }
    }
}
    
fn main() {
    let mut v = (Vec::new(), Vec::new());
    ExtendTuple(&mut v).extend((0..12).tuples());
    println!("{:?}", v);
}
```

**Comment by bluss** [comment]
Interesting discussion, but I think we decided the partition by index thing is sufficiently covered by partition_map, and what's more we can make interesting Extend impls for various tuple wrappers, but that's not necessarily in scope for itertools.
