### ISSUE TITLE
Do not assert(n == 0) in combinations and yield one empty vector instead

### ISSUE THREAD

**Issue by nagisa** [bluss/rust-itertools#174]
Consider a case like this:

```
it.flat_map(|v| (0..v).combinations(x))
```

This iterator panics if `it` happens to yield a `0`. I feel like it would be much more convenient if the combinations iterator just didn’t yield anything (i.e. was the same as an iterator that always yields None).

**Comment by bluss** [comment]
Your example code is showing the input iterator being empty (`0..v` with `v = 0`) if I understand correctly, and combinations is already yielding `None` there.

**Comment by nagisa** [comment]
Oh, I swapped variables mistakenly.

It was supposed to be

```
it.flat_map(|v| (0..x).combinations(v))
```

instead. For all its worth, Python returns one empty tuple in this case:

```
list(itertools.combinations([1, 2, 3], 0))
[()]
```

**Comment by bluss** [comment]
A precedent is worth something

**Comment by bluss** [comment]
If we do this, it breaks the documented promise of panicking for `n == 0` in `.combinations()`. It seems the reasonable thing is to emit one empty vector for `n == 0`, not no iterator elements?

**Comment by nagisa** [comment]
> It seems the reasonable thing is to emit one empty vector for n == 0, not no iterator elements?

Yes. This behaviour would also retain the fact that number of distinct combinations is equal to a binomial coefficient (n choose 0 = 1, for any n).
