### ISSUE TITLE
Seekable Iterators

### ISSUE THREAD

**Issue by burdges** [bluss/rust-itertools#181]
Anyone considered adding seekable iterators?  I'm asking because some stream ciphers like ChaCha20 have a seek function.

I'm not sure iterators would provide a safe interface to stream ciphers anyways.  It's probably fine though because the `next` function only branches on stream length, once to extract a new block of output from the cipher, and once to return `None` if the cipher was really exhausted.  I'd envision one iterator mode of a stream cipher that just outputs the blocks anyways, avoiding these first of these.

**Comment by bluss** [comment]
What does safety entail? Do you think of it as in the constant time sense?

Having iterators that seek in general seems like a natural extension. Is it something that seekable iterators have in common though, that they should share that in a trait?

Discussion here should eventually be actionable issues about itertools. There are so many things one can do with iterators that don't have their home here; this crate is just about general iterator adaptors and utilities.

**Comment by burdges** [comment]
I *think* safety means not branching, or doing memory accesses, based on actual key material.  It should be okay to do branches or memory accesses based on key material length, so an iterator should be fine.  

There are obviously iterator functions like filter or whatever that won't be safe, so maybe an iterator `impl` interacts with key material wrapper structs meant to help prevent improper usage. 

I donno if itertools would want a seekable iterator trait or not, but I'd kinda imagined so.  ;)

**Comment by bluss** [comment]
No I want to emphasize there's a *ton* of things to do with iterators that are not homed here. New trait concepts, random access iterators, etc should have their own projects.

**Comment by burdges** [comment]
I'll close this issues and write a seekable trait for iterators crate if I wind up wanting one.
