### ISSUE TITLE
Add some sort of iterator that groups elements

### ISSUE THREAD

**Issue by Slabity** [bluss/rust-itertools#190]
One issue I had was the need to count how many of each item is in an iterator. Given an iterator that returns the following: `[-10, -4, -4, 3, 3, 3, 8, 10, 10, 10, 10]`, I'd like to be able to create another iterator that returns the counts of each value: `[1, 2, 3, 1, 4]`

The best solution I could think of right now is pushing an unused value to the end of the list and using `coalesce` to try and bring it together, filtering out the last element:

```rust
    let my_vec = vec![-10, -4, -4, 3, 3, 3, 8, 10, 10, 10, 10, i32::min_value()];

    let mut count = 1;
    let abomination = my_vec.into_iter()
        .coalesce(|x, y|
            if x == y {
                count += 1;
                Ok(x)
            } else {
                let ret = count;
                count = 1;
                Err((ret, y))
            }).filter(| &x | x != i32::min_value());
```

This is definitely not a clean way to do it. Perhaps someone else can figure out a clean method of doing so.

**Comment by gregwebs** [comment]
You could use `group_by` and `map`.

**Comment by Slabity** [comment]
Wow. I can't believe I didn't find `group_by` before. Thanks.

**Comment by gregwebs** [comment]
It doesn't show up in top level documentation. I am not sure why

**Comment by bluss** [comment]
It's a method in the Itertools trait, which is the heart of the crate
