### ISSUE TITLE
Add kmerge_by

### ISSUE THREAD

**Issue by cbrewster** [bluss/rust-itertools#191]
Hi there!

I have a scenario where I have multiple iterators and would like to join them via a kmerge; however, currently I would need to implement `Ord` for my type. This becomes hard as the sorting is only relevant to the specific algorithm generating this iterator. I don't want to have `Ord` implemented for the type as it will behave differently based on the scenario.

Would it be possible to be able to pass a closure to something like `kmerge_by` to determine the ordering?

**Comment by bluss** [comment]
Yes. It requires some refactoring but the binary heap implementation is bespoke, which means we can easily extend its functionality in this way.

On the same bill I'd like to place the wish that it should only require PartialOrd in the default (`.kmerge()`) implementation.

**Comment by bluss** [comment]
Do you have feedback on the design in the linked PR?

**Comment by cbrewster** [comment]
@bluss initial read-through looks pretty good. Thanks for doing this!
