### ISSUE TITLE
Add IntoChunks for chars

### ISSUE THREAD

**Issue by beamspease** [bluss/rust-itertools#193]
I get this error when trying to call chunks() on chars():
`"the method 'map' exists but the following trait bounds were not satisfied: 'itertools::IntoChunks<core:tr::Chars<'_>> : core::iter::Iterator'"`

**Comment by bluss** [comment]
Ah it exists, the confusing fact is that IntoChunks is not an iterator (but iterable). Need to call into_iter() on it.

https://docs.rs/itertools/0.5.9/itertools/trait.Itertools.html#method.chunks
