### ISSUE TITLE
`GroupBy` iterator should have better size_hint

### ISSUE THREAD

**Issue by antiguru** [bluss/rust-itertools#202]
Currently, the `GroupBy` iterator returns keyed groups where `Group` implements `Iterator` behavior. Because of this, it has a function `size_hint`. This function always returns `(0, None)`, the most general size hint possible. It would be nice if this size hint would be more accurate. (A simple improvement would be to return `(1, None)` as a group is never empty.)

**Comment by bluss** [comment]
The size hint must always be correct, also when the iterator has been partially walked, so (1, None) is for example not right after a group of one element has had one element consumed (remaining size is 0)

I've previously decided that we can't do better for group by, but that could be wrong of course, please say if you find a good way, please open a new issue or ask to reopen this one.

See also issue #171 which is for the simpler case -- chunks.
