### ISSUE TITLE
A ScopedTake adaptor

### ISSUE THREAD

**Issue by golddranks** [bluss/rust-itertools#210]
Something I just scratched together for a need in my code:

http://play.integer32.com/?gist=bd6b2f8cbfa38ff785ecb5ba06e85822&version=stable

This is an iterator adaptor that doesn't consume another iterator like they usually do, but takes only a mutable reference to an iterator, behaves like "take" and draws values from the other iterator, but after you are done with it and have disposed of it, you can continue using the original iterator from where it was iterated to.

It's helpful in pipelined situations where you have an iterator you don't want to consume totally, but for example, do a chunk of work, and then the hand the results to another "phase" of work, and a bit later, loop back to continuing iterating the the original iterator.

I'd like to see it as a part of Itertools. Do you think it would fit in?

**Comment by bluss** [comment]
Hey — we have a native way to accomplish this (unless I'm missing some subtle thing), which is the iterator implementation for `&mut I` and the regular take. It should be equivalent. 

[playground example](http://play.integer32.com/?gist=322472b212fa1acc7c6849384d086894&version=stable)

**Comment by golddranks** [comment]
Ah, I mistakenly thought that the `&mut I` iterator would returns `&mut Items`, but it returns owned `Items`! So, indeed, this was a needless complication. Thanks!
