### ISSUE TITLE
[feature request] collect that lifts Option from elements to the Vec.

### ISSUE THREAD

**Issue by derekdreery** [bluss/rust-itertools#213]
Here's a function definition if it were stand-alone and not part of the trait:

```rust
/// Takes an iterator over options and if any are `None`, returns `None` otherwise returns `Some(vec)` 
/// where vec is the iterator with all elements unwrapped
fn lift_option<I, T>(i: I) -> Option<Vec<T>>
where I: Iterator<Item=Option<T>>
{
    ...
}
```

with something similar for Result. What do you think?

**Comment by bluss** [comment]
Something similar is coming for Result, see PR #203

**Comment by derekdreery** [comment]
Maybe consider implementing for Option as well, there are valid use cases other than lazy error handling :)

**Comment by bluss** [comment]
If it's just collect, I should tell you that Rust already includes this: https://doc.rust-lang.org/nightly/std/option/enum.Option.html#method.from_iter

A generic Iterator can't be walked more than once -- so there is no way to only collect after having looked at all elements to ensure they are Somes -- we can only look at each element once if we don't save them.

**Comment by bluss** [comment]
Ok, with that this request has been fulfilled, it's in standard Rust.
