### ISSUE TITLE
Iterator adaptor .positions(predicate)

### ISSUE THREAD

**Issue by bluss** [bluss/rust-itertools#218]
Like an iterated version of position or a filtered version of enumerate.

The existing combination is a bit heavy on the punctuation:

```rust
self.1.iter()
      .enumerate()
      .filter(|&(_, node)| node.weight.is_none())
      .map(|(i, _)| NodeIndex::<Ix>::new(i))
```

Propose instead:

```rust
self.1.iter()
      .positions(|node| node.weight.is_none())
      .map(NodeIndex::<Ix>::new)
```

**Comment by bluss** [comment]
An alternative, a literal filtered version of enumerate. Indices are including the removed elements, of course.

```rust
self.1.iter()
      .enumerate_filter(|node| node.weight.is_none())
      .map(|(i, _node)| NodeIndex::<Ix>::new(i))
```

**Comment by tmccombs** [comment]
I prefer the positions interface, because it is easier to use in situations like

```rust
let positions = self.1.iter().positions().collect();
```
