### ISSUE TITLE
Iterator trait requirements are asymmetric and seem overly restrictive

### ISSUE THREAD

**Issue by H2CO3** [bluss/rust-itertools#220]
If sets `A` and `B` have a Cartesian product `A × B`, then so should exist the transposed product, `B × A`. However, while the following minimal code compiles:

```
#[macro_use]
extern crate itertools;

fn main() {
    let ax = &[1];
    let a = (0..ax.len() + 1).map(|n| &ax[..n]);
    let b = &[2];

    iproduct!(a, b);
}
```
the one that differs only in the order of arguments to the `iproduct!` macro doesn't:

```
#[macro_use]
extern crate itertools;

fn main() {
    let ax = &[1];
    let a = (0..ax.len() + 1).map(|n| &ax[..n]);
    let b = &[2];

    iproduct!(b, a);
}
```
In the latter case, the compiler complains that

> the trait bound `[closure@src/main.rs:6:35: 6:47 ax:_]: std::clone::Clone` is not satisfied

This seems an odd asymmetry to have (and it just prevented me from writing an actual Cartesian product in a similar, although non-trivial case).

**Comment by bluss** [comment]
The only way to make it symmetric is to add the same restriction on both sides, which is then more restrictions than we need. Rust is a language where we are explicit about cloning or holding multiple handles to a value, so it's hard to get around it, and in many applications of cartesian_product it's downright useful to have one side that doesn't have to be clonable at all -- like in your example code.

Do you have a proposal for a concrete change we chan do to our implementation? PRs are welcome, albeit we particularly prefer patches that are not breaking changes, then we don't need to gnash on hard decisions for very long!

**Comment by bluss** [comment]
Note: You can make your own cartesian product using `Iterator::flat_map`, then instead of the clone-y way, you provide a closure that knows how to make a new iterator for each element of the base iterator.

**Comment by H2CO3** [comment]
@bluss 
> You can make your own cartesian product using `Iterator::flat_map`

Sure, but for an 8-tuple, that's not nearly as nice/obvious as `iproduct!`, that's why I am using this create in the first place.

Anyway, if there's no way to lift these restrictions, that's fine; I just thought that there could have been a small oversight, but apparently that is not the case.

**Comment by bluss** [comment]
Ok cool.

I don't want to be a super downer, but I think an 8-tuple in iproduct will have performance problems. Itertools is a bit here and there when it comes to performance; some adaptors are "zero cost" and some are not, and some depend on usage.

What I remain wary of is the difficulty the compiler has in taking an iterator's "state machine" that is simulating multiple nested loops, and reverse that and compile it as actual, nested, loops. It's a hard problem! The iterator design and its next method dictates that we go through a model that is purely linear -- there is only a next element.

The sum of that experience is that flat_map, cartesian_product are not "zero-cost", they are in fact costly. Iterators are not ideal when it comes to simulating nested loops. One way to alleviate it is using `fold`, `for_each` etc, if the iterators special case the fold method -- `flat_map` does.

**Comment by H2CO3** [comment]
In fact I don't think that would matter at all. I'm using it in a test suite where possible cases are tried out independently, hence the Cartesian product. The suite generates about 1000-1500 test cases (no property has more than 4 possible values currently, most of them are just present/absent `bool`s), so it runs in the blink of an eye.

**Comment by bluss** [comment]
Yeah that makes sense

**Comment by H2CO3** [comment]
Thanks for the heads up anyway. I'll keep your advice in mind in case I'll need itertools in a performance-sensitive context. 👍
