### ISSUE TITLE
Group_by trait bounds

### ISSUE THREAD

**Issue by Phlosioneer** [bluss/rust-itertools#224]
In the Itertools trait, group_by has the following definition:
```
fn group_by<K, F>(self, key: F) -> GroupBy<K, Self, F>
  where
    Self: Sized,
    F: FnMut(&Self::Item) -> K
```
It then simply creates a new GroupBy struct. The only method on the GroupBy struct is into_iter, which has the following definition for the GroupBy struct:
```
impl<'a, K, I, F> IntoIterator for &'a GroupBy<K, I, F> 
  where
    I: Iterator,
    I::Item: 'a,
    F: FnMut(&I::Item) -> K,
    K: PartialEq, 
```

So in order to _use_ group_by, K must implement PartialEq; but that fact is not evident in the definition of the group_by function (No trait bounds on K).

Should it be added to group_by?

I ran into this issue when K was a struct; I had to jump through the documentation to understand why K didn't typecheck, and where rustc was getting the trait bound.

**Comment by Phlosioneer** [comment]
Side note: this would only be a breaking change in the case where someone calls group_by and then never uses it. (because into_iter would never be called, so there would be no typechecking necessary)

**Comment by bluss** [comment]
Yes it should be added. We can do it in the next incompatible version
