### ISSUE TITLE
Use small-vec::VecLike over Vec to prevent std dependency where possible.

### ISSUE THREAD

**Issue by djmcgill** [bluss/rust-itertools#230]
I'd love it if I could use these tools in a libstd free environment and currently the use of Vec is hard-coded for the backing storage.

Is there interest from making the storage type be a (static generic parameter that implements) [VecLike](https://docs.rs/smallvec/0.5.0/smallvec/trait.VecLike.html) trait where possible? The default type could be Vec so it'd be entirely backwards compatible I think.

Pros:
- Can use this library in an environment without libstd,
- Might allow more efficient use of this library by avoiding heap allocations.

Cons:
- Complicates implementation,
- Adds a generic type to the interface, complicating error messages and possibly use,
- Non-std Rust is currently niche at best.

Alternatives:
- A different trait instead of VecLike
- Do nothing
- Could implement the iterators in a macro, allowing them to be made generic over the storage without exposing it to the end-user.

**Comment by bluss** [comment]
Note that new in itertools 0.7 was that it finally does support std-free environments. But yes, all the things that need Vec or similar are then removed, without substitute.

The idea sounds good, but we need a high quality dependency for the collection traits, and that's a rather tricky requirement. I also don't know a way to supply a default in a way that is backwards compatible like you suggest.

(I haven't looked around what kind of interface we actually need to a "vec", per functionality, but it could be interesting to look at that for a single item.)
