### ISSUE TITLE
Iterator trait for group by?

### ISSUE THREAD

**Issue by PSeitz** [bluss/rust-itertools#246]
I need to do several calculations on a group, but because of the missing Iterator Trait on groupBy, it seems this is not possible, since the values are moved on the first operation.

Something like this:
https://play.rust-lang.org/?gist=3e436f6363c19997c9053cfe6b407fbe&version=stable

```rust
extern crate itertools;

use std::cmp;
use itertools::Itertools;
fn main() {


    let  token_hits = vec![(1, 0.3, 3),(1, 0.6, 6),(4, 1.0, 3),(7, 0.3, 13)];
    
    for (parent_id, group) in &token_hits.into_iter().group_by(|el| el.0) {
        let max = group.max_by_key(|el| el.2).unwrap().2;
        println!("{:?}", max);
        let scores = group.map(|el| el.1).collect_vec();
        println!("{:?}", scores);
    }
    
}

**Comment by bluss** [comment]
It's not related to the missing iterator trait I think. `group` is one iterator, and you can't iterate it twice, just like all other iterators.

**Comment by PSeitz** [comment]
Okay thanks, so it's possible with `let (mut t1, t2) = group.tee();`

I think it's a litte confusing, that the docs mention explicitly that GroupBy is not an iterator https://docs.rs/itertools/0.7.4/itertools/structs/struct.GroupBy.html

**Comment by bluss** [comment]
In your code, this expression is the `GroupBy`: `token_hits.into_iter().group_by(|el| el.0)`

it *yields* tuples of the group key and the [`Group`](https://docs.rs/itertools/0.7.4/itertools/structs/struct.Group.html) iterator. That's a different iterator. That's the iterator for the elements of a group.
