### ISSUE TITLE
fold_results feels underpowered?

### ISSUE THREAD

**Issue by kivikakk** [bluss/rust-itertools#247]
I've been using the current definition (which happened to share a name with itertools' method!) internally:

```rust
pub fn fold_results<I, B, F, R, E>(it: I, init: B, mut f: F) -> Result<B, E>
where
    I: Iterator<Item = R>,
    F: FnMut(B, R) -> Result<B, E>,
{
    let mut acc = init;
    for i in it {
        match f(acc, i) {
            Err(e) => return Err(e),
            Ok(acc_) => acc = acc_,
        }
    }
    Ok(acc)
}
```

Right now the itertools `fold_results` can be approximated with `it.collect::<Result<Vec<_>, _>>().map(|v| v.fold(…))`, but the above can't be done. This probably needs another name, but feels like it belongs? This is essentially Haskell's `foldM`.

**Comment by bluss** [comment]
No underpowered, just a different thing. Your version is unstable in Rust, called `Iterator::try_fold`. I think that means this is (eventually) covered by Rust.
