### ISSUE TITLE
group_until the predicate

### ISSUE THREAD

**Issue by l4l** [bluss/rust-itertools#248]
Maybe name is not really suitable because it doesn't really similar to `group_by`

The idea is to make groups until the predicate returns true. E.g if we has `(0..10)`
Calling `group_until(|x| x%3 == 0 && x != 0)`
Should return an iterator over:
```
[
  [0,1,2,3],
  [4,5,6],
  [7,8,9]
]
```

I find [split](https://doc.rust-lang.org/std/primitive.slice.html#method.split)/[splitn](https://doc.rust-lang.org/std/primitive.slice.html#method.splitn) in std, but it does remove the elements.
And I didn't find anything useful in itertools, maybe missed something?

**Comment by bluss** [comment]
`.group_by` can do that with the correct closure, but it's not super simple to realize maybe.

Here's an example where the group key is incremented *after* each time we find an elt divisible by three.

```rust
let mut i = 0u64;
iterator.group_by(|elt| {
    let current = i;
    i += ((*elt % 3) == 0 && *elt != 0) as u64;
    current
})
```

**Comment by bluss** [comment]
I think with that, we kind of cover it well enough using `.group_by`?

**Comment by l4l** [comment]
Looks interesting, yeah and for my case quite better solution
Also I don't really have any opinion on that (is it enough to have group_by) so maybe there's some other drawbacks except an additional variable

**Comment by bluss** [comment]
Yes I think group_by is complex enough that we don't want to duplicate it. Unless we invent a smarter way to specify how to do the grouping, for example with a generic argument to `.group_by` where it takes a closure now. Inventions welcome, anyone with one can open a new issue for discussion.
