### ISSUE TITLE
Rust isn't recognising itertools.

### ISSUE THREAD

**Issue by WarpspeedSCP** [bluss/rust-itertools#252]
I added itertools to `cargo.toml`, then tried to use the library like normal, but it doesn't work! When I try to compile, cargo complains that the import in not recognised, and suggests `self::itertools::Itertools` for the line `use itertools::Itertools;`. How do I get it to import!? I'm on v1.24 nightly.

**Comment by bluss** [comment]
Either use the suggested line, or move your "extern crate itertools" line to the root file of your crate. HTH

**Comment by WarpspeedSCP** [comment]
so, that would be `main.rs` or `lib.rs`?

**Comment by bluss** [comment]
I encourage experimentation -- if you have 2 candidates, you can easily try both and see what happens. Please use discussion forums or irc for more questions.

**Comment by WarpspeedSCP** [comment]
Ahh, thank you. Sorry for the trouble!
