### ISSUE TITLE
Different types in FoldWhile

### ISSUE THREAD

**Issue by Noctune** [bluss/rust-itertools#259]
Currently, FoldWhile requires the same type in `Continue` and `Done`, but it doesn't seem obvious why it shouldn't be able to use two different types.

It might be possible to add in a backwards compatible way, for example by adding the second type as a type parameter defaulting to the first type parameter.

**Comment by bluss** [comment]
Marking as breaking-change so that it is not forgotten at a breaking change-point.

**Comment by bluss** [comment]
Note that std `Itertools::try_fold` will give you what you want, I think.

**Comment by Noctune** [comment]
Yeah, that seems like it would do exactly what I want. It does feel a little dirty to use `Err` for things that aren't really errors, so something like `FoldWhile` would still be nice if it implemented `Try` when it eventually stabilizes. However, I'll just use `try_fold` with `Err` for now, so thanks!

**Comment by scottmcm** [comment]
> It does feel a little dirty to [...]

I agree -- core uses an enum very much like FoldWhile internally to make things clearer: https://github.com/rust-lang/rust/blob/master/src/libcore/iter/mod.rs#L356-L404

**Comment by bluss** [comment]
`.fold_while()` has been deprecated in favour of `.try_fold`, and that's why this change is not implemented. It could otherwise easily be implemented.
