### ISSUE TITLE
feature proposal: map_is_last

### ISSUE THREAD

**Issue by Ekleog** [bluss/rust-itertools#273]
I've been annoyed a number of times with the impossibility to know, when iterating, whether we are at the last element or not.

So I've finally written the following iterator adapter, that does just like `map` but adds as an argument whether the element being mapped is the last one or not:
```rust
struct MapIsLast<I: Iterator, F> {
    iter: std::iter::Peekable<I>,
    f: F
}

impl<R, I: Iterator, F: FnMut(I::Item, bool) -> R> Iterator for MapIsLast<I, F> {
    type Item = R;

    #[inline]
    fn next(&mut self) -> Option<R> {
        let res = self.iter.next();
        let is_last = self.iter.peek().is_none();
        res.map(|x| (self.f)(x, is_last))
    }

    #[inline]
    fn size_hint(&self) -> (usize, Option<usize>) {
        self.iter.size_hint()
    }
}

fn map_is_last<R, I: Iterator, F: FnMut(I::Item, bool) -> R>(iter: I, f: F) -> MapIsLast<I, F> {
    MapIsLast { iter: iter.peekable(), f }
}
```

Would you be interested in a PR to itertools to add this iterator adapter?

**Comment by bluss** [comment]
The with_position adaptor already covers this use case, albeit in a different way. Check if there is something we can do with with_position to make it easy to use for you.

**Comment by Ekleog** [comment]
Oh I hadn't seen `with_position` in my search for the docs!

It works perfectly, thanks! So closing this, as I don't think there is much that could be done (apart maybe from improving search from the docs? I had intuitively thought `with_position` was similar to `enumerate`, at first, so I guess I didn't even read the docs)

Anyway, sorry for the noise, and thanks for your work!

**Comment by bluss** [comment]
with_position was written by @luser
