### ISSUE TITLE
Support for `From::from` on the items of iterator

### ISSUE THREAD

**Issue by vorner** [bluss/rust-itertools#280]
Hello

I find myself writing iterator method chains that contain `map(From::from)` ‒ I need to convert all the elements from one type to another. I was wondering, if there are convenience methods like `cloned` (I think that one is actually in std already) and `collect_vec`, would it make sense to have some kind of convenience method for this? I could send a pull request, but I want to ask first if it makes sense to anyone else and if someone has a good name for such method.

**Comment by tobz1000** [comment]
`.map_from()`? ;)

**Comment by vorner** [comment]
I thought about that one, but it felt… unsatisfying. What I mean is:

* For example, we have `cloned`, not `map_clone`.
* I wonder if `map_into` (or somethingelse`_into`) would be better, because if I want to convert things, I can either do `Result::from(source)` or `source.into()` ‒ and in case of the iterator it would be in the postfix method notation.
* I also thought about `converted` (either `intoed` or `fromed` sounds silly), but I don't know if people would reasonably find that one.
