### ISSUE TITLE
Put common usage /use cases/ examples that this crate helps to fix 

### ISSUE THREAD

**Issue by allan-simon** [bluss/rust-itertools#33]
Some examples in the readme or the doc  will be greatly appreciable , as it improve the discoverabiltiy of your lib , especially for guys like me that are just wondering "hmmmm should i use it ?" 

thanks for the lib.

**Comment by bluss** [comment]
I will fix this. Until then, there are [examples for each method](http://bluss.github.io/rust-itertools/doc/itertools/trait.Itertools.html#method.batching) in the docs

**Comment by allan-simon** [comment]
yes, thanks, they are pretty useful :)
