### ISSUE TITLE
Is there a function to do the SQL equivalent of COUNT(*) GROUP BY

### ISSUE THREAD

**Issue by allan-simon** [bluss/rust-itertools#34]
for example i have a vector of value 

```
[ 'a'  , 'a' ,  'b' , 'c', 'c' 'c']
```

and it returns me a hashmap 

```
[
   'a' => 2
  'b' => 1 
  'c' =>  3
]

```

**Comment by bluss** [comment]
I don't think we have that. Solution without itertools:


```rust
use std::collections::HashMap;
"aabccc".chars().fold(HashMap::new(), |mut m, c| { *m.entry(c).or_insert(0) += 1; m })
// Output: {'a': 2, 'c': 3, 'b': 1}
```

**Comment by allan-simon** [comment]
awesome, thanks a lot man, i was using a naive solution with simple iterators .

Regarding the ticket itself, if you think it's outside of the scope of itertools, feel free to close the ticket.

**Comment by bluss** [comment]
I'm not sure it's outside the scope. I would wish we could solve this relatively generically, so for example supporting all kinds of maps as return value. We don't have the traits to do that yet in rust.
