### ISSUE TITLE
Find a good example for .while_some()

### ISSUE THREAD

**Issue by bluss** [bluss/rust-itertools#35]
This new adaptor [`.while_some()` (commit, not yet merged)](https://github.com/bluss/rust-itertools/commit/d461775a28f665a11b46d868fb019e7b572c0071) needs a nice example + test.

@DanielKeep Is this the iterator we decided was missing? The missing part to turn an infinite iteration of None's into a sensible iterator.

**Comment by DanielKeep** [comment]
That looks like it'd do it.  It does have one downside: the need to explicitly unpack the `Option<A>` to generate the next element, but that's not *insurmountable*, and hopefully shouldn't be a big optimisation problem.

Here's [a really basic example](https://play.rust-lang.org/?gist=372a505d34f5079b85d8&version=nightly), rewritten slightly to fit the playpen.

**Comment by bluss** [comment]
True, that is a big downside.
You could use mutable state (much uglier in your eyes I presume).

```rust
let mut n = 0;
let ns = WhileSome::new((0..).map(move |_| if n <= 5 { let nn = n; n += 1; Some(nn) } else { None }))
```

**Comment by DanielKeep** [comment]
In that case, I'd prefer to go with the `Option::and_then` approach.  I mean, iterator chaining is fundamentally about chaining operations together in a linear expression; having to break out and create state storage is (for me, at least) a heavy push toward "maybe I should just do this with a `for` loop".

Unless I was doing *a lot* of these, I'd probably just live with the `Option::and_then`.  Having this lowers the effort barrier enough that, had this already existed, I wouldn't have bothered to make my own adaptor.  :)
