### ISSUE TITLE
Make Stride use RandomAccessIterators

### ISSUE THREAD

**Issue by awelkie** [bluss/rust-itertools#4]
As it is now, the Stride struct only operates on slices. We can instead make the Stride struct use any iterator that implements the RandomAccessIterator trait. The benefits of doing this are that we can stride over more than just slices, the Stride struct should be simpler, and we won't need to use unsafe blocks. 

I thought there might be a performance decrease in switching to RandomAccessIterator-based strides, especially when composing strides. I implemented the RandomAccessIterator-based strides, and there is indeed a performance drop when compiling without optimization. However, when compiling with optimization (level 2), the RandomAccessIterator-based stride actually performs better than the slice-based stride, often by at least a factor of 2. I have the tests at awelkie/rust-itertools on the "stride_performance" branch. 

Would you mind checking my performance comparison? If the RandomAccessIterator-based strides are indeed faster with optimization, and you think it's a good idea, then I would be happy to re-implement the Stride struct.

**Comment by bluss** [comment]
Please file a PR if a RAI solution is created.
