### ISSUE TITLE
'sorted()' method

### ISSUE THREAD

**Issue by zummenix** [bluss/rust-itertools#54]
It would be useful to have `sorted()` method for regular sorting that calls `sorted_by(Ordering::cmp)` internally. What do you think?

**Comment by bluss** [comment]
Yes in the long run. Right now due to #49 it feels like we can't really use functions like this profitably, and supporting another variant is some more code. See how I'm trying to solve it in #53.

**Comment by bluss** [comment]
A sorted() method is still a good idea, it was the unrelated breaking changes that were declined in #71.
