### ISSUE TITLE
Is there a function equivalent to SQL inner join?

### ISSUE THREAD

**Issue by phil-n** [bluss/rust-itertools#56]
As a rust newbie coming from C#, I was wondering if there's any function equivalent to [this](https://msdn.microsoft.com/en-us/library/system.linq.enumerable.join%28v=vs.90%29.aspx).
I was looking through the docs of itertools and std::iter and couldn't find anything related.

Thanks in advance

**Comment by bluss** [comment]
There isn't, but this project has it: [contain-rs/ordered_iter](https://github.com/contain-rs/ordered_iter).

**Comment by phil-n** [comment]
Nice, thanks!

**Comment by scottmcm** [comment]
I think this is now possible with `.merge_join_by( ... ).filter_map(|x| if let Both(x) = x { Some(x) } else { None })`, assuming the input iterators are sorted first.

**Comment by bluss** [comment]
Yes merge_join_by came out really nice. We might want to add convenience methods to EitherOrBoth

**Comment by bluss** [comment]
Thanks @scottmcm, let's say that merge_join_by covers this and ergonomics improvements can be applied to the existing functionality.  Fixed by #228
