### ISSUE TITLE
Add a .windows(n) iterator adapter

### ISSUE THREAD

**Issue by flo-l** [bluss/rust-itertools#64]
Similar to [```.windows()```](https://doc.rust-lang.org/std/primitive.slice.html#method.windows) in std, just not only for slices but for arbitrary iterators. I saw that ```.chunks()``` is already implemented as ```chunks_lazy()```. Would you find eg. ```windows_lazy()``` implemented in a similar fashion useful?

I've read the code of ```chunks_lazy()```, it's quite complicated. But with a few hints from somebody who knows the code I could probably implement ```windows_lazy()``` myself.

**Comment by bluss** [comment]
I haven't thought about this too deeply, but it would require a lot of copying of iterator elements? Since each element appears in several windows. It might not be bad at all, when applied to usual by-reference iterators like the slice iterator.

**Comment by bluss** [comment]
I'll be assigned just to keep the issue on my radar. (Feel free to implement this if you want). Not sure how easy it's to translate GroupByLazy's model to windows..

**Comment by flo-l** [comment]
ok I'll give it a try as soon as I find time!

**Comment by bluss** [comment]
A link to https://crates.io/crates/iterslide came up when browsing /r/rust

**Comment by flo-l** [comment]
sorry for the long response time, university is tough sometimes!

This crate looks like the exact thing I want in itertools! Should the author be asked for their permission to include the code or should I reimplement it?

**Comment by bluss** [comment]
It's very wasteful by cloning so much, not sure if I like its approach.

**Comment by flo-l** [comment]
ok you're right it clones the whole vec on each iteration :disappointed:

I'll give it a try and code something in the weekend and open a pr here! (hopefully without being as wasteful)

**Comment by flo-l** [comment]
I gave it some thought and found a problem.

I wanted to implement it like so: Have the adapter struct store the current window in a vec and let next() return a slice of that vec.

This is impossible because the iterator protocol allows this:

```rust
let it = other_it.windows_adapter(3);
let slice_a = it.next();
let slice_b = it.next();
```

Clearly the second call to next() invalidates slice_a.

I think it could be implemented utilizing a RefCell or a custom type providing similar functionality. The user then had to make sure slice_a isn't used after the second call to next().

Any thoughts?

**Comment by bluss** [comment]
A solution parametrized by arrays would be awesome, but I guess it would dictate compile time window sizes, which does not fit all use cases.

Then how to solve the borrowing problem.. it's certainly expected, and iterslide uses cloning to not run into it.

A separation of storage vs the iterator is usually the precursor to any solution. Maybe there's something cool that can be done with an interior-mutable type like you suggest? Preferable would be to have it transparently deref to slice, even though it would have to be panicky... Not sure what itertools' stance should be on that.

**Comment by flo-l** [comment]
One could write a macro for windows with sizes known at compile time!

My idea regarding the borrowing problem: the user has to supply a reference to a storage to the adapter when it's created where it stores the window. (And possible other data as well).

To make this ergonomic a custom type encapsulating all needed information is probably a good idea. Also a macro could make the initialization of the storage type a lot more convenient.

I tried to codify this, but I have not yet firgured out how to convince rustc this is safe -.-

Anyway, that's how user code could look like:

```rust
let it = (0..100);

let window = Window::new(3);
let window = window!(3); // macro? (for optional arguments)
let window = window!(container -> 3); // maybe let the user optionally recycle some already existing container

let windowed_iter = it.windows(window);

// this would be nice too
let windowed_iter = windowed!(it -> 3);

// could this be possible?
let windowed_iter = it.windows(window!(3));
```

**Comment by bluss** [comment]
I think itertools should go ahead with the vec! / Clone approach, just like combinations_n and group_by. Just need to find a good way to document it. Might also want a vecless special case for a window of 2.

**Comment by flo-l** [comment]
I think so too, the windows iterator with windows of any size can not be as efficient as it should be, so there could be special cases for up to `n` elements in the window, but not more.

One can mimic the functionality for larger windows by collecting into a vec and using its `.windows()` iterator. Actually what [`sliding_windows`](https://github.com/flo-l/rust-sliding_windows) does is only more efficient for **very** large iterators in terms of memory usage. (Eg. endless iterators can't be used with the collect approach obviously)
