### ISSUE TITLE
Why the extra impl for ZipSlices?

### ISSUE THREAD

**Issue by SuperFluffy** [bluss/rust-itertools#67]
I was looking at the [`ZipSlices` impl](https://github.com/bluss/rust-itertools/blob/master/src/zipslices.rs#L28-L64) and noticed that you have the signatures `
impl<'a, 'b, A, B> ZipSlices<&'a [A], &'b [B]>` and `impl<T, U> ZipSlices<T, U> where T: Slice, U: Slice`. The latter seems a lot more general, and I was wondering why the former is still in the library? Are there some non-trivial reasons for this?

**Comment by bluss** [comment]
Yes, the reason is that the non-general one will force coercions, so it will actually work with arguments like '&Vec<T>`, so it's actually easier to use. Only problem is I've basically inverted the names for the two methods..

**Comment by bluss** [comment]
If type parameter defaults change the story for coercions, we can talk about removing it, until then it's useful.

**Comment by bluss** [comment]
Type param defaults: rust-lang/rust/issues/27336
