### ISSUE TITLE
Add function to convert Option<IntoIterator> into Iterator

### ISSUE THREAD

**Issue by awelkie** [bluss/rust-itertools#77]
I've run into a situation where I could use a function that takes an `Option<T>` where `T: IntoIterator` and return a struct that implements the `Iterator` trait. The behavior would be the same as the contained iterator, or `std::iter::Empty` if there is no contained iterator.

First of all, is there any way to do this without defining a new struct? If not, would this function be a useful addition to itertools? I'm willing to do the implementation, I just wanted to get the go-ahead first.

**Comment by bluss** [comment]
`.into_iter().flat_map(|x| x)`  (flat map with the identity function) will do this for you.

**Comment by awelkie** [comment]
Yep, that's perfect. Thanks!
