### ISSUE TITLE
Add minmax/minmax_by_key

### ISSUE THREAD

**Issue by birkenfeld** [bluss/rust-itertools#79]
Sometimes I'd like to keep track of minimum and maximum without iterating twice (if that's even possible). Itertools might be a good place for such adapters?

**Comment by bluss** [comment]
yes, that sounds good! We just need to pick a name that doesn't conflict with std. I guess they don't have minmax right now?

**Comment by birkenfeld** [comment]
I haven't seen anything that is called `minmax` there. I don't know if there is a "mathematically nicer" name though :)

I'll have a go at a pull request.

**Comment by bluss** [comment]
These are in now.
