### ISSUE TITLE
RepeatCall shouldn't implement DoubleEndedIterator

### ISSUE THREAD

**Issue by Stebalien** [bluss/rust-itertools#86]
For example, the following iterator is definitely not reservable:

```rust
RepeatCall::new({
    let mut counter = 0;
    move || {
        counter += 1;
        counter
    }
});
```

**Comment by bluss** [comment]
I guess you're right about that, most implementations do not make sense as double ended. You can of course run into this problem in other places, like in a regular `.iter().map()` too.

**Comment by Stebalien** [comment]
That's... odd. I've submitted a bug to discuss it (https://github.com/rust-lang/rust/issues/30632). It kind of makes sense because map (and filter) are generally pure functions but should, at least, be noted. 

However, this case is pretty clear; `RepeatCall` always produces an infinite sequence and infinite sequences only have one end.

**Comment by bluss** [comment]
I disagree actually, infinite sequences can have two ends (For example .cycle()). Maybe cycle is a bad argument, since I wrote it :smile:

**Comment by bluss** [comment]
Oh no, cycle is not double ended! My evil plans,... Ok I guess I managed to scare you there by mistake.

**Comment by bluss** [comment]
On the whole, side effectful iterators can always cause trouble like this. I'm leaning towards wontfixing this bug for this reason, it has use cases where double endedness is useful.

**Comment by Stebalien** [comment]
> Infinite sequences have one end.

-- ZFC

Yes, some sequences can go backwards from the starting point but that's not double ended, it's no-ended (doubly infinite).

**Comment by bluss** [comment]
I thought this issue could stay open until we make a decision (0.5 is next breaking change opportunity).

Currently I lean WONTFIX.

**Comment by bluss** [comment]
In a crazy turn of events, I'm removing the DEI implementation in 0.5
