### ISSUE TITLE
Breaking changes in 0.5

### ISSUE THREAD

**Issue by bluss** [bluss/rust-itertools#87]
- [x] #86 
- [x] Possibly depend on use crate either  #129
- [x] Remove .map_fn(), MapFn
- [x] Remove .mend_slices
- [x] ~~Remove reexports `itertools::{enumerate, rev}` (exist in the free module)~~
- [x] Remove .into_rc()
- [x] Remove .sort_by (deprecated)
- [x] Remove ZipSlices (doesn't live up to its perf promise anymore due to optimizer changes)
- [x] Remove ZipTrusted (will have new life with specialization)
- [x] Rename Group by lazy and chunks lazy?
- [x] Remove Stride/StrideMut? Are separate crate material
- [x] Remove Linspace (doesn't work properly without using crate num-traits)
- [x] ~~Remove itertools::equal (Iterator.eq is the same).~~
- [x] Remove dropn (can't use .nth() like dropping does).

**Comment by bluss** [comment]
Updated with proposed removals

**Comment by bluss** [comment]
- [ ] Migrate from Struct::new to free function constructors

This is a tricky case of consistency. The libstd sets a precedence by functions like `std::iter::once`.

The argument for a free function is that the iterator's functionality is much more important than the identity of the type/struct involved.

The argument for Struct::new (for example `RcIter::new` and so on) is that it is consistent with other rust structs.

Candidates:

- `Zip::new` -> `zip` or `multizip`
- `RcIter::new` -> `rciter`
- probably more

**Comment by Robbepop** [comment]
In my opinion, Zip::new(it1, it2, ...) is a superior syntax to it1.multizip(it2, ...). Of course this is a subjective matter but for a generalized zip with multiple parameters (and not just one as in the std lib) it just fits better.
However, for chaining of iterators the std-lib version fits better.
So in the end, maybe supporting both versions may be the best idea?

**Comment by bluss** [comment]
the mentioned `multizip` would be a free function, not a method. Either way, both of them need to use a tuple, so the actual syntax is `Zip::new((it1, it2, ..))` or `multizip((it1, it2, ..))`.

**Comment by Robbepop** [comment]
I like the idea very much in general. (free all the functions !! =D)

However, it isn't a Rusty-API style as you have mentioned above.

Replacing the old-syntax with the new would be a breaking change, I guess, so if you really implement this feature you would choose between breaking stuff or supporting both APIs for a while.

**Comment by bluss** [comment]
Will be a breaking change, that's why it's planned in advance in this issue.

**Comment by Robbepop** [comment]
As far as I have understood the itertools trait is for supporting iterator chaining, right?

If that is further supported besides the new free-functions (which cannot be chained if I am correct) the resuting API would have no disadvantages over the current one.

At least in some cases there would be clearer semantics behind the code as you have stated above with which I totally agree: "The argument for a free function is that the iterator's functionality is much more important than the identity of the type/struct involved."


So the only question is consistency versus sanity ...

**Comment by bluss** [comment]
Fixed, 0.5.0 has been released
